name: "Deploy to Nest"
author: "Arnav Kumar"
branding:
  icon: "feather"
  color: "black"
description: "Deploy to your Nest instance as a Docker container"

runs:
  using: composite
  steps:
    - name: Pull latest changes
      shell: bash
      id: pull
      run: |
        delimiter="$(openssl rand -hex 8)"
        {
        echo 'pull-output<<${delimiter}'
        curl -sSH 'Authorization: ${{ inputs.deployToken }}' ${{ inputs.deployUrl }}/pull
        echo '${delimiter}'
        } >> "$GITHUB_OUTPUT"
    - name: Build Docker image
      shell: bash
      id: build
      run: |
        delimiter="$(openssl rand -hex 8)"
        {
        echo 'deployment-status<<${delimiter}'
        curl -sSH 'Authorization: ${{ inputs.deployToken }}' ${{ inputs.deployUrl }}/build
        echo '${delimiter}'
        } >> "$GITHUB_OUTPUT"
    - name: Deploy Docker image
      shell: bash
      id: deploy
      run: |
        delimiter="$(openssl rand -hex 8)"
        {
        echo 'pull-output<<${delimiter}'
        curl -sSH 'Authorization: ${{ inputs.deployToken }}' ${{ inputs.deployUrl }}/run
        echo '${delimiter}'
        } >> "$GITHUB_OUTPUT"
inputs:
  deployToken:
    description: "Your Project Deploy Token from nest-deploy cli"
    required: true
  deployUrl:
    description: "Your Project Deploy URL from nest-deploy cli"
    required: true
outputs:
  pull-output:
    description: "The output of the git pull command (comes from stdout)"
    value: "${{ steps.pull.outputs.pull-output }}"
  build-output:
    description: "Docker build output"
    value: "${{ steps.build.outputs.build-output }}"
  deployment-status:
    description: "If the deployment was successful or not"
    value: "${{ steps.deploy.outputs.deployment-status }}"
