name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Nest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run
        uses: ./
        with:
          deployUrl: ${{ secrets.DEPLOY_URL }}
          deployToken: ${{ secrets.DEPLOY_TOKEN }}